### PR TITLE
Create backend models

### LINKED ISSUE #21: Implement Models
- [ ] User
- [ ] Repository
- [ ] File
- [ ] Review
- [ ] Feedback

### PR DESCRIPTION
**Pull request by johnsgill3**
This resolves #21.

### CODE REVIEW

**Comment by johnsgill3** [comment]
Still need to write tests for models.

@ryanbmilbourne Can you please make sure models (and schema.rb) are correct based on wiki.

**Comment by johnsgill3** [comment]
@ryanbmilbourne Okay. I think I've got the basic modeling finished as well as the basic test infrastructure.

The only thing I am a little worried about is the association between Repository and Review. I changed the repository association to be through files: `has_many :reviews, through: :g_files`. But because there is a many-to-many association between files and reviews (`has_and_belongs_to_many :g_files`) the only way that there to do the reverse from review to repository would be to use a `has_many :repositories, through :g_files`. This removes the duplication of having a `repository_id` in the reviews table, but this puts requirement to check that the number of repositories for a single review is only 1. I could look at adding a `validates :repositories, length: { maximum: 1 }`. 

Thoughts?

**Comment by ryanbmilbourne** [comment]
The only thing that concerns me is the reverse from Review to Repository.  `has_many :repositories` seems wrong from a review perspective, since a Review belongs to only one repo... I suppose it could be me misunderstanding Postgres associations but that seems rather counter-intuitive to me.

**Comment by johnsgill3** [comment]
I completely agree about the `has_many` being the wrong type of association.
I was just trying to reduce the FK maintenance by allowing Repositories and Reviews be related to each other through files. PG doesn't care, it's rails that doesn't like the syntax due to the many-to-many between files and reviews.

I say we just leave it as is for now and if in development of the insertions we can always tweak backend model relationships as we need to.

If you think all the models/tests look good merge whenever.

**Comment by ryanbmilbourne** [comment]
sounds good to me.

**Pull request merged**
